Expand and update accise_energie_metropole
openfisca/openfisca-france-indirect-taxation pull request #183
Opened 2024-06-21 13:47 UTC by benoit-cty

Expand and update accise_energie_metropole

2024-06-25 14:50 UTC, Hervedarr31 requested changes
Petites erreurs de certaines valeurs.

2024-06-25 14:50 UTC, Hervedarr31 commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/carbureacteurs.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603787
ref suggérée : https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000048833665/2022-01-01/

2024-06-25 14:50 UTC, Hervedarr31 commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/essence_aviation.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603677
ref suggérée : https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000046869423/2022-01-01/

2024-06-25 14:50 UTC, Hervedarr31 commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/essences.yaml
> +    value: 74.576
2022-01-01 
    value : 76.826
2024-01-01 
    value : 76.826
2024-01-01 
    value : 76.826

ref : https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603787/2022-01-01/
https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603787/2023-01-01/
https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603787/2024-01-01/

2024-06-25 14:50 UTC, Hervedarr31 commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/fiouls_domestiques.yaml
> +    value: 15.686
value : 15.62
2023-01-01 : 
    value : 15.62
2024-01-01 : 
    value : 15.62

2024-06-25 14:50 UTC, Hervedarr31 commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/fiouls_domestiques.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603785
https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603785/2022-01-01/
2023-01-01 : 
    href : https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603785/2023-01-01/
2024-01-01 : 
    href : https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603785/2024-01-01/

2024-06-25 14:50 UTC, Hervedarr31 commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/gazoles_travaux_statiques.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603787
href : https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603787/2022-01-01/

2024-06-25 14:50 UTC, Hervedarr31 commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/gn_combustible.yaml
> +    value: 5.189
value : 8.45

2024-06-28 09:33 UTC, benoit-cty commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/gn_combustible.yaml
> +    value: 5.189
Merci, j'avais fait confiance au fichier d'origine : https://github.com/openfisca/openfisca-france-indirect-taxation/blob/8614238429dddc7b0052317ac206bde2af1aa0eb/openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole.yaml#L160

C'est corrigé.

2024-06-28 09:33 UTC, benoit-cty commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/gazoles_travaux_statiques.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603787
Merci, corrigé.

2024-06-28 09:33 UTC, benoit-cty commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/fiouls_domestiques.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603785
Merci, corrigé.

2024-06-28 09:33 UTC, benoit-cty commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/fiouls_domestiques.yaml
> +    value: 15.686
Merci, corrigé.

2024-06-28 09:33 UTC, benoit-cty commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/essences.yaml
> +    value: 74.576
Merci, corrigé.

2024-06-28 09:33 UTC, benoit-cty commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/essence_aviation.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603677
Merci, corrigé.

2024-06-28 09:33 UTC, benoit-cty commented on openfisca_france_indirect_taxation/parameters/imposition_indirecte/produits_energetiques/accise_energie_metropole/carbureacteurs.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044603787
Merci, corrigé.

2024-06-28 13:50 UTC, Hervedarr31 approved these changes

2024-06-28 13:51 UTC, benoit-cty commented
Merci beaucoup Hervé pour ta vigilance dans la revue.

2024-06-28 13:52 UTC, merged